services:
  - type: worker
    name: maythusharmusicvv3
    env: python
    region: frankfurt
    plan: standard
    buildCommand: pip3 install --no-cache-dir --upgrade --requirement requirements.txt
    startCommand: bash start
    envVars:
      - key: API_ID
        value: "23596049"
      - key: API_HASH
        value: "62c2019123d852fc8cc2092ca879f31c"
      - key: BOT_TOKEN
        value: "7892011487:AAEgqHEy3x9TUgZ7i9LZaaz4vDO6v3Pv0EU"
      - key: MONGO_DB_URI
        value: "mongodb+srv://wanglin:wanglin@wanglin.ppt93bd.mongodb.net/?retryWrites=true&w=majority"
      - key: OWNER_ID
        value: "6940535380"
      - key: LOGGER_ID
        value: "-1001901470191"
      - key: STRING_SESSION
        value: "BQFoDBEArtikhUPMxnqgDEOP66B4SNXFo9gZpd7SPOt_Gsa5tVwM0KnHhwe8AaFFzROhR6vD5htGc1y_8YpQil-FhPGY8IXXp0qEyP0CyyaX5PDm8fw54non08llLqroIAJ7zA9sW0sZ1yzapAN0jjyPvukn0sFHLt84YchAAaqIWumpVuHq1NbYGEXHiMu4TEe-gxpf-Y2sJkTlmKGeN37rMIGG1xrmq2NkwMtXsh90KBrJS6KccKmwKjRraiwLA0mJTe3qTzP23nqe7udGDn40LnbfLdrD9MhuLuU5aSpw63GKTDzfg8C689M4_5xpR1PuuaCKSnyyz9ORjWpCUEg8g6WmRAAAAAFQk4y9AA"
